// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file jobconfigpb/embedded.proto (package dev.reduction.jobconfig, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jobconfigpb/embedded.proto.
 */
export const file_jobconfigpb_embedded: GenFile = /*@__PURE__*/
  fileDesc("Chpqb2Jjb25maWdwYi9lbWJlZGRlZC5wcm90bxIXZGV2LnJlZHVjdGlvbi5qb2Jjb25maWci0QEKDkVtYmVkZGVkU291cmNlEhMKC3NwbGl0X2NvdW50GAEgASgFEhIKCmJhdGNoX3NpemUYAiABKAUSSAoJZ2VuZXJhdG9yGAMgASgOMjUuZGV2LnJlZHVjdGlvbi5qb2Jjb25maWcuRW1iZWRkZWRTb3VyY2UuR2VuZXJhdG9yVHlwZSJMCg1HZW5lcmF0b3JUeXBlEh4KGkdFTkVSQVRPUl9UWVBFX1VOU1BFQ0lGSUVEEAASGwoXR0VORVJBVE9SX1RZUEVfU0VRVUVOQ0UQAUIuWixyZWR1Y3Rpb24uZGV2L3JlZHVjdGlvbi1wcm90b2NvbC9qb2Jjb25maWdwYmIGcHJvdG8z");

/**
 * @generated from message dev.reduction.jobconfig.EmbeddedSource
 */
export type EmbeddedSource = Message<"dev.reduction.jobconfig.EmbeddedSource"> & {
  /**
   * @generated from field: int32 split_count = 1;
   */
  splitCount: number;

  /**
   * @generated from field: int32 batch_size = 2;
   */
  batchSize: number;

  /**
   * @generated from field: dev.reduction.jobconfig.EmbeddedSource.GeneratorType generator = 3;
   */
  generator: EmbeddedSource_GeneratorType;
};

/**
 * Describes the message dev.reduction.jobconfig.EmbeddedSource.
 * Use `create(EmbeddedSourceSchema)` to create a new message.
 */
export const EmbeddedSourceSchema: GenMessage<EmbeddedSource> = /*@__PURE__*/
  messageDesc(file_jobconfigpb_embedded, 0);

/**
 * @generated from enum dev.reduction.jobconfig.EmbeddedSource.GeneratorType
 */
export enum EmbeddedSource_GeneratorType {
  /**
   * @generated from enum value: GENERATOR_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GENERATOR_TYPE_SEQUENCE = 1;
   */
  SEQUENCE = 1,
}

/**
 * Describes the enum dev.reduction.jobconfig.EmbeddedSource.GeneratorType.
 */
export const EmbeddedSource_GeneratorTypeSchema: GenEnum<EmbeddedSource_GeneratorType> = /*@__PURE__*/
  enumDesc(file_jobconfigpb_embedded, 0, 0);

