// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file jobconfigpb/httpapi.proto (package dev.reduction.jobconfig, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { StringVar } from "./resolvable_pb";
import { file_jobconfigpb_resolvable } from "./resolvable_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jobconfigpb/httpapi.proto.
 */
export const file_jobconfigpb_httpapi: GenFile = /*@__PURE__*/
  fileDesc("Chlqb2Jjb25maWdwYi9odHRwYXBpLnByb3RvEhdkZXYucmVkdWN0aW9uLmpvYmNvbmZpZyJRCg1IVFRQQVBJU291cmNlEjAKBGFkZHIYASABKAsyIi5kZXYucmVkdWN0aW9uLmpvYmNvbmZpZy5TdHJpbmdWYXISDgoGdG9waWNzGAIgAygJIj8KC0hUVFBBUElTaW5rEjAKBGFkZHIYASABKAsyIi5kZXYucmVkdWN0aW9uLmpvYmNvbmZpZy5TdHJpbmdWYXJCLloscmVkdWN0aW9uLmRldi9yZWR1Y3Rpb24tcHJvdG9jb2wvam9iY29uZmlncGJiBnByb3RvMw", [file_jobconfigpb_resolvable]);

/**
 * @generated from message dev.reduction.jobconfig.HTTPAPISource
 */
export type HTTPAPISource = Message<"dev.reduction.jobconfig.HTTPAPISource"> & {
  /**
   * @generated from field: dev.reduction.jobconfig.StringVar addr = 1;
   */
  addr?: StringVar;

  /**
   * @generated from field: repeated string topics = 2;
   */
  topics: string[];
};

/**
 * Describes the message dev.reduction.jobconfig.HTTPAPISource.
 * Use `create(HTTPAPISourceSchema)` to create a new message.
 */
export const HTTPAPISourceSchema: GenMessage<HTTPAPISource> = /*@__PURE__*/
  messageDesc(file_jobconfigpb_httpapi, 0);

/**
 * @generated from message dev.reduction.jobconfig.HTTPAPISink
 */
export type HTTPAPISink = Message<"dev.reduction.jobconfig.HTTPAPISink"> & {
  /**
   * @generated from field: dev.reduction.jobconfig.StringVar addr = 1;
   */
  addr?: StringVar;
};

/**
 * Describes the message dev.reduction.jobconfig.HTTPAPISink.
 * Use `create(HTTPAPISinkSchema)` to create a new message.
 */
export const HTTPAPISinkSchema: GenMessage<HTTPAPISink> = /*@__PURE__*/
  messageDesc(file_jobconfigpb_httpapi, 1);

