// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file jobconfigpb/kinesis.proto (package dev.reduction.jobconfig, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { StringVar } from "./resolvable_pb";
import { file_jobconfigpb_resolvable } from "./resolvable_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jobconfigpb/kinesis.proto.
 */
export const file_jobconfigpb_kinesis: GenFile = /*@__PURE__*/
  fileDesc("Chlqb2Jjb25maWdwYi9raW5lc2lzLnByb3RvEhdkZXYucmVkdWN0aW9uLmpvYmNvbmZpZyJ9Cg1LaW5lc2lzU291cmNlEjYKCnN0cmVhbV9hcm4YASABKAsyIi5kZXYucmVkdWN0aW9uLmpvYmNvbmZpZy5TdHJpbmdWYXISNAoIZW5kcG9pbnQYAiABKAsyIi5kZXYucmVkdWN0aW9uLmpvYmNvbmZpZy5TdHJpbmdWYXJCLloscmVkdWN0aW9uLmRldi9yZWR1Y3Rpb24tcHJvdG9jb2wvam9iY29uZmlncGJiBnByb3RvMw", [file_jobconfigpb_resolvable]);

/**
 * @generated from message dev.reduction.jobconfig.KinesisSource
 */
export type KinesisSource = Message<"dev.reduction.jobconfig.KinesisSource"> & {
  /**
   * @generated from field: dev.reduction.jobconfig.StringVar stream_arn = 1;
   */
  streamArn?: StringVar;

  /**
   * @generated from field: dev.reduction.jobconfig.StringVar endpoint = 2;
   */
  endpoint?: StringVar;
};

/**
 * Describes the message dev.reduction.jobconfig.KinesisSource.
 * Use `create(KinesisSourceSchema)` to create a new message.
 */
export const KinesisSourceSchema: GenMessage<KinesisSource> = /*@__PURE__*/
  messageDesc(file_jobconfigpb_kinesis, 0);

