// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file jobconfigpb/memory.proto (package dev.reduction.jobconfig, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jobconfigpb/memory.proto.
 */
export const file_jobconfigpb_memory: GenFile = /*@__PURE__*/
  fileDesc("Chhqb2Jjb25maWdwYi9tZW1vcnkucHJvdG8SF2Rldi5yZWR1Y3Rpb24uam9iY29uZmlnIgwKCk1lbW9yeVNpbmtCLloscmVkdWN0aW9uLmRldi9yZWR1Y3Rpb24tcHJvdG9jb2wvam9iY29uZmlncGJiBnByb3RvMw");

/**
 * @generated from message dev.reduction.jobconfig.MemorySink
 */
export type MemorySink = Message<"dev.reduction.jobconfig.MemorySink"> & {
};

/**
 * Describes the message dev.reduction.jobconfig.MemorySink.
 * Use `create(MemorySinkSchema)` to create a new message.
 */
export const MemorySinkSchema: GenMessage<MemorySink> = /*@__PURE__*/
  messageDesc(file_jobconfigpb_memory, 0);

