// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file jobconfigpb/stdio.proto (package dev.reduction.jobconfig, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jobconfigpb/stdio.proto.
 */
export const file_jobconfigpb_stdio: GenFile = /*@__PURE__*/
  fileDesc("Chdqb2Jjb25maWdwYi9zdGRpby5wcm90bxIXZGV2LnJlZHVjdGlvbi5qb2Jjb25maWciQAoLU3RkaW9Tb3VyY2USMQoHZnJhbWluZxgBIAEoCzIgLmRldi5yZWR1Y3Rpb24uam9iY29uZmlnLkZyYW1pbmci5wEKB0ZyYW1pbmcSTgoObGVuZ3RoX2VuY29kZWQYASABKAsyNC5kZXYucmVkdWN0aW9uLmpvYmNvbmZpZy5GcmFtaW5nLkxlbmd0aEVuY29kZWRTY2hlbWVIABJFCglkZWxpbWl0ZWQYAiABKAsyMC5kZXYucmVkdWN0aW9uLmpvYmNvbmZpZy5GcmFtaW5nLkRlbGltaXRlZFNjaGVtZUgAGhUKE0xlbmd0aEVuY29kZWRTY2hlbWUaJAoPRGVsaW1pdGVkU2NoZW1lEhEKCWRlbGltaXRlchgBIAEoDEIICgZzY2hlbWUiCwoJU3RkaW9TaW5rQi5aLHJlZHVjdGlvbi5kZXYvcmVkdWN0aW9uLXByb3RvY29sL2pvYmNvbmZpZ3BiYgZwcm90bzM");

/**
 * @generated from message dev.reduction.jobconfig.StdioSource
 */
export type StdioSource = Message<"dev.reduction.jobconfig.StdioSource"> & {
  /**
   * @generated from field: dev.reduction.jobconfig.Framing framing = 1;
   */
  framing?: Framing;
};

/**
 * Describes the message dev.reduction.jobconfig.StdioSource.
 * Use `create(StdioSourceSchema)` to create a new message.
 */
export const StdioSourceSchema: GenMessage<StdioSource> = /*@__PURE__*/
  messageDesc(file_jobconfigpb_stdio, 0);

/**
 * Framing specifies how to separate messages for the stdio source
 *
 * @generated from message dev.reduction.jobconfig.Framing
 */
export type Framing = Message<"dev.reduction.jobconfig.Framing"> & {
  /**
   * @generated from oneof dev.reduction.jobconfig.Framing.scheme
   */
  scheme: {
    /**
     * @generated from field: dev.reduction.jobconfig.Framing.LengthEncodedScheme length_encoded = 1;
     */
    value: Framing_LengthEncodedScheme;
    case: "lengthEncoded";
  } | {
    /**
     * @generated from field: dev.reduction.jobconfig.Framing.DelimitedScheme delimited = 2;
     */
    value: Framing_DelimitedScheme;
    case: "delimited";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message dev.reduction.jobconfig.Framing.
 * Use `create(FramingSchema)` to create a new message.
 */
export const FramingSchema: GenMessage<Framing> = /*@__PURE__*/
  messageDesc(file_jobconfigpb_stdio, 1);

/**
 * @generated from message dev.reduction.jobconfig.Framing.LengthEncodedScheme
 */
export type Framing_LengthEncodedScheme = Message<"dev.reduction.jobconfig.Framing.LengthEncodedScheme"> & {
};

/**
 * Describes the message dev.reduction.jobconfig.Framing.LengthEncodedScheme.
 * Use `create(Framing_LengthEncodedSchemeSchema)` to create a new message.
 */
export const Framing_LengthEncodedSchemeSchema: GenMessage<Framing_LengthEncodedScheme> = /*@__PURE__*/
  messageDesc(file_jobconfigpb_stdio, 1, 0);

/**
 * @generated from message dev.reduction.jobconfig.Framing.DelimitedScheme
 */
export type Framing_DelimitedScheme = Message<"dev.reduction.jobconfig.Framing.DelimitedScheme"> & {
  /**
   * @generated from field: bytes delimiter = 1;
   */
  delimiter: Uint8Array;
};

/**
 * Describes the message dev.reduction.jobconfig.Framing.DelimitedScheme.
 * Use `create(Framing_DelimitedSchemeSchema)` to create a new message.
 */
export const Framing_DelimitedSchemeSchema: GenMessage<Framing_DelimitedScheme> = /*@__PURE__*/
  messageDesc(file_jobconfigpb_stdio, 1, 1);

/**
 * @generated from message dev.reduction.jobconfig.StdioSink
 */
export type StdioSink = Message<"dev.reduction.jobconfig.StdioSink"> & {
};

/**
 * Describes the message dev.reduction.jobconfig.StdioSink.
 * Use `create(StdioSinkSchema)` to create a new message.
 */
export const StdioSinkSchema: GenMessage<StdioSink> = /*@__PURE__*/
  messageDesc(file_jobconfigpb_stdio, 2);

