// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file testrunpb/testrun.proto (package dev.reduction.testrun, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { KeyedEvent, KeyEventBatchRequest, ProcessEventBatchRequest } from "../handlerpb/handler_pb";
import { file_handlerpb_handler } from "../handlerpb/handler_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file testrunpb/testrun.proto.
 */
export const file_testrunpb_testrun: GenFile = /*@__PURE__*/
  fileDesc("Chd0ZXN0cnVucGIvdGVzdHJ1bi5wcm90bxIVZGV2LnJlZHVjdGlvbi50ZXN0cnVuIsQBCg1SdW5uZXJDb21tYW5kEj8KD2FkZF9rZXllZF9ldmVudBgBIAEoCzIkLmRldi5yZWR1Y3Rpb24udGVzdHJ1bi5BZGRLZXllZEV2ZW50SAASPAoNYWRkX3dhdGVybWFyaxgCIAEoCzIjLmRldi5yZWR1Y3Rpb24udGVzdHJ1bi5BZGRXYXRlcm1hcmtIABIpCgNydW4YAyABKAsyGi5kZXYucmVkdWN0aW9uLnRlc3RydW4uUnVuSABCCQoHY29tbWFuZCKlAQoOSGFuZGxlckNvbW1hbmQSRwoTcHJvY2Vzc19ldmVudF9iYXRjaBgBIAEoCzIoLmRldi5yZWR1Y3Rpb24udGVzdHJ1bi5Qcm9jZXNzRXZlbnRCYXRjaEgAEj8KD2tleV9ldmVudF9iYXRjaBgCIAEoCzIkLmRldi5yZWR1Y3Rpb24udGVzdHJ1bi5LZXlFdmVudEJhdGNoSABCCQoHY29tbWFuZCJHCg1BZGRLZXllZEV2ZW50EjYKC2tleWVkX2V2ZW50GAEgASgLMiEuZGV2LnJlZHVjdGlvbi5oYW5kbGVyLktleWVkRXZlbnQiDgoMQWRkV2F0ZXJtYXJrIgUKA1J1biJpChFQcm9jZXNzRXZlbnRCYXRjaBJUChtwcm9jZXNzX2V2ZW50X2JhdGNoX3JlcXVlc3QYASABKAsyLy5kZXYucmVkdWN0aW9uLmhhbmRsZXIuUHJvY2Vzc0V2ZW50QmF0Y2hSZXF1ZXN0Il0KDUtleUV2ZW50QmF0Y2gSTAoXa2V5X2V2ZW50X2JhdGNoX3JlcXVlc3QYASABKAsyKy5kZXYucmVkdWN0aW9uLmhhbmRsZXIuS2V5RXZlbnRCYXRjaFJlcXVlc3RCLFoqcmVkdWN0aW9uLmRldi9yZWR1Y3Rpb24tcHJvdG9jb2wvdGVzdHJ1bnBiYgZwcm90bzM", [file_handlerpb_handler]);

/**
 * @generated from message dev.reduction.testrun.RunnerCommand
 */
export type RunnerCommand = Message<"dev.reduction.testrun.RunnerCommand"> & {
  /**
   * @generated from oneof dev.reduction.testrun.RunnerCommand.command
   */
  command: {
    /**
     * @generated from field: dev.reduction.testrun.AddKeyedEvent add_keyed_event = 1;
     */
    value: AddKeyedEvent;
    case: "addKeyedEvent";
  } | {
    /**
     * @generated from field: dev.reduction.testrun.AddWatermark add_watermark = 2;
     */
    value: AddWatermark;
    case: "addWatermark";
  } | {
    /**
     * @generated from field: dev.reduction.testrun.Run run = 3;
     */
    value: Run;
    case: "run";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message dev.reduction.testrun.RunnerCommand.
 * Use `create(RunnerCommandSchema)` to create a new message.
 */
export const RunnerCommandSchema: GenMessage<RunnerCommand> = /*@__PURE__*/
  messageDesc(file_testrunpb_testrun, 0);

/**
 * @generated from message dev.reduction.testrun.HandlerCommand
 */
export type HandlerCommand = Message<"dev.reduction.testrun.HandlerCommand"> & {
  /**
   * @generated from oneof dev.reduction.testrun.HandlerCommand.command
   */
  command: {
    /**
     * @generated from field: dev.reduction.testrun.ProcessEventBatch process_event_batch = 1;
     */
    value: ProcessEventBatch;
    case: "processEventBatch";
  } | {
    /**
     * @generated from field: dev.reduction.testrun.KeyEventBatch key_event_batch = 2;
     */
    value: KeyEventBatch;
    case: "keyEventBatch";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message dev.reduction.testrun.HandlerCommand.
 * Use `create(HandlerCommandSchema)` to create a new message.
 */
export const HandlerCommandSchema: GenMessage<HandlerCommand> = /*@__PURE__*/
  messageDesc(file_testrunpb_testrun, 1);

/**
 * @generated from message dev.reduction.testrun.AddKeyedEvent
 */
export type AddKeyedEvent = Message<"dev.reduction.testrun.AddKeyedEvent"> & {
  /**
   * @generated from field: dev.reduction.handler.KeyedEvent keyed_event = 1;
   */
  keyedEvent?: KeyedEvent;
};

/**
 * Describes the message dev.reduction.testrun.AddKeyedEvent.
 * Use `create(AddKeyedEventSchema)` to create a new message.
 */
export const AddKeyedEventSchema: GenMessage<AddKeyedEvent> = /*@__PURE__*/
  messageDesc(file_testrunpb_testrun, 2);

/**
 * @generated from message dev.reduction.testrun.AddWatermark
 */
export type AddWatermark = Message<"dev.reduction.testrun.AddWatermark"> & {
};

/**
 * Describes the message dev.reduction.testrun.AddWatermark.
 * Use `create(AddWatermarkSchema)` to create a new message.
 */
export const AddWatermarkSchema: GenMessage<AddWatermark> = /*@__PURE__*/
  messageDesc(file_testrunpb_testrun, 3);

/**
 * @generated from message dev.reduction.testrun.Run
 */
export type Run = Message<"dev.reduction.testrun.Run"> & {
};

/**
 * Describes the message dev.reduction.testrun.Run.
 * Use `create(RunSchema)` to create a new message.
 */
export const RunSchema: GenMessage<Run> = /*@__PURE__*/
  messageDesc(file_testrunpb_testrun, 4);

/**
 * @generated from message dev.reduction.testrun.ProcessEventBatch
 */
export type ProcessEventBatch = Message<"dev.reduction.testrun.ProcessEventBatch"> & {
  /**
   * @generated from field: dev.reduction.handler.ProcessEventBatchRequest process_event_batch_request = 1;
   */
  processEventBatchRequest?: ProcessEventBatchRequest;
};

/**
 * Describes the message dev.reduction.testrun.ProcessEventBatch.
 * Use `create(ProcessEventBatchSchema)` to create a new message.
 */
export const ProcessEventBatchSchema: GenMessage<ProcessEventBatch> = /*@__PURE__*/
  messageDesc(file_testrunpb_testrun, 5);

/**
 * @generated from message dev.reduction.testrun.KeyEventBatch
 */
export type KeyEventBatch = Message<"dev.reduction.testrun.KeyEventBatch"> & {
  /**
   * @generated from field: dev.reduction.handler.KeyEventBatchRequest key_event_batch_request = 1;
   */
  keyEventBatchRequest?: KeyEventBatchRequest;
};

/**
 * Describes the message dev.reduction.testrun.KeyEventBatch.
 * Use `create(KeyEventBatchSchema)` to create a new message.
 */
export const KeyEventBatchSchema: GenMessage<KeyEventBatch> = /*@__PURE__*/
  messageDesc(file_testrunpb_testrun, 6);

