// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file handlerpb/handler.proto (package dev.reduction.handler, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { KeyEventBatchRequest, KeyEventBatchResponse, ProcessEventBatchRequest, ProcessEventBatchResponse } from "./handler_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service dev.reduction.handler.Handler
 */
export const Handler = {
  typeName: "dev.reduction.handler.Handler",
  methods: {
    /**
     * @generated from rpc dev.reduction.handler.Handler.ProcessEventBatch
     */
    processEventBatch: {
      name: "ProcessEventBatch",
      I: ProcessEventBatchRequest,
      O: ProcessEventBatchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dev.reduction.handler.Handler.KeyEventBatch
     */
    keyEventBatch: {
      name: "KeyEventBatch",
      I: KeyEventBatchRequest,
      O: KeyEventBatchResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

